"""
Security Audit Dashboard
A Flask-based web interface to visualize container security audit results
"""

from flask import Flask, render_template, jsonify, send_file, request
import json
from pathlib import Path
import sys
from datetime import datetime
import shutil
import subprocess

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from realtime_threat_engine import RuntimeThreatEngine

app = Flask(__name__)

REPORTS_DIR = PROJECT_ROOT / "reports"
RUNTIME_DIR = PROJECT_ROOT / "runtime"


def run_shell(command, cwd=PROJECT_ROOT):
    """Run a shell command and return completed process."""
    return subprocess.run(command, cwd=cwd, shell=True, capture_output=True, text=True)


def list_containers():
    """Return a list of active Docker containers using docker CLI."""
    if not shutil.which("docker"):
        return []

    result = run_shell("docker ps --format '{{json .}}'")
    if result.returncode != 0:
        return []

    containers = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            containers.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return containers


def tool_status():
    """Collect available security tool statuses."""
    tools = ["docker", "trivy", "dockle", "syft", "grype", "python"]
    return {tool: bool(shutil.which(tool)) for tool in tools}


def runtime_engine_instance():
    """Create runtime engine instance for on-demand report generation."""
    return RuntimeThreatEngine(config_path=str(PROJECT_ROOT / "config.yaml"))


def runtime_summary_by_container(name: str):
    data = load_runtime_findings()
    for item in data.get("findings", []):
        if item.get("name") == name:
            return item
    return None


def load_latest_report():
    """Load the most recent audit report"""
    history_file = REPORTS_DIR / "audit_history.json"
    
    if history_file.exists():
        with open(history_file, 'r') as f:
            history = json.load(f)
            if history:
                return history[-1]
    
    return None


def load_history():
    """Load all historical audit data"""
    history_file = REPORTS_DIR / "audit_history.json"
    
    if history_file.exists():
        with open(history_file, 'r') as f:
            return json.load(f)
    
    return []


def load_runtime_findings():
    """Load latest runtime threat findings generated by runtime engine"""
    runtime_file = RUNTIME_DIR / "runtime_threats_latest.json"

    if runtime_file.exists():
        with open(runtime_file, 'r') as f:
            return json.load(f)

    return {
        "generated_at": None,
        "summary": {
            "containers_monitored": 0,
            "critical_alerts": 0,
            "high_alerts": 0,
            "medium_alerts": 0,
            "low_alerts": 0
        },
        "findings": []
    }


@app.route('/')
def index():
    """Main dashboard page"""
    report = load_latest_report()
    runtime = load_runtime_findings()
    return render_template('dashboard.html', report=report, runtime=runtime)


@app.route('/api/latest')
def api_latest():
    """API endpoint for latest report"""
    report = load_latest_report()
    if report:
        return jsonify(report)
    return jsonify({"error": "No reports available"}), 404


@app.route('/api/history')
def api_history():
    """API endpoint for historical data"""
    history = load_history()
    return jsonify(history)


@app.route('/api/trends')
def api_trends():
    """API endpoint for trend analysis"""
    history = load_history()
    
    if not history:
        return jsonify({"error": "No historical data"}), 404
    
    trends = {
        "dates": [],
        "vulnerable_size": [],
        "hardened_size": [],
        "vulnerable_vulns": [],
        "hardened_vulns": []
    }
    
    for entry in history:
        timestamp = entry.get('timestamp', '')
        if timestamp:
            trends["dates"].append(timestamp[:10])  # Just date part
        
        comp = entry.get('comparison', {})
        trends["vulnerable_size"].append(float(comp.get('size_vulnerable_mb', 0)))
        trends["hardened_size"].append(float(comp.get('size_hardened_mb', 0)))
        trends["vulnerable_vulns"].append(comp.get('vuln_vulnerable', 0))
        trends["hardened_vulns"].append(comp.get('vuln_hardened', 0))
    
    return jsonify(trends)


@app.route('/api/runtime-threats')
def api_runtime_threats():
    """API endpoint for latest runtime threat findings"""
    return jsonify(load_runtime_findings())


@app.route('/api/control-panel/status')
def api_control_panel_status():
    """Control panel status summary for security tooling and outputs."""
    runtime_file = RUNTIME_DIR / "runtime_threats_latest.json"
    runtime_exists = runtime_file.exists()
    return jsonify({
        "timestamp": datetime.now().isoformat(),
        "tools": tool_status(),
        "runtime_output_exists": runtime_exists,
        "runtime_output_path": str(runtime_file),
        "runtime_generated_at": load_runtime_findings().get("generated_at") if runtime_exists else None,
        "containers_running": len(list_containers()),
        "ai_model_loaded": Path("../ai_security_model.py").exists(),
        "vuln_monitor_enabled": True
    })


@app.route('/api/control-panel/containers')
def api_control_panel_containers():
    """List running containers for control panel management."""
    return jsonify({"containers": list_containers()})


@app.route('/api/control-panel/runtime/snapshot', methods=['POST'])
def api_control_panel_runtime_snapshot():
    """Trigger a one-shot runtime threat snapshot."""
    cmd = "RUNTIME_MONITOR_MODE=once python realtime_threat_engine.py"
    result = run_shell(cmd)
    return jsonify({
        "success": result.returncode == 0,
        "command": cmd,
        "stdout": result.stdout[-2000:],
        "stderr": result.stderr[-2000:],
        "exit_code": result.returncode
    }), (200 if result.returncode == 0 else 500)


@app.route('/api/control-panel/audit/run', methods=['POST'])
def api_control_panel_run_audit():
    """Trigger a security audit run from the control panel."""
    cmd = "python audit.py"
    result = run_shell(cmd)
    return jsonify({
        "success": result.returncode == 0,
        "command": cmd,
        "stdout": result.stdout[-3000:],
        "stderr": result.stderr[-3000:],
        "exit_code": result.returncode
    }), (200 if result.returncode == 0 else 500)


@app.route('/api/control-panel/container-action', methods=['POST'])
def api_control_panel_container_action():
    """Apply start/stop/restart actions to a container."""
    data = request.get_json(silent=True) or {}
    container = data.get("container")
    action = data.get("action")

    if action not in {"start", "stop", "restart"}:
        return jsonify({"success": False, "error": "Invalid action"}), 400
    if not container:
        return jsonify({"success": False, "error": "Container is required"}), 400

    cmd = f"docker {action} {container}"
    result = run_shell(cmd)
    return jsonify({
        "success": result.returncode == 0,
        "container": container,
        "action": action,
        "stdout": result.stdout[-2000:],
        "stderr": result.stderr[-2000:],
        "exit_code": result.returncode
    }), (200 if result.returncode == 0 else 500)


@app.route('/api/runtime-threats/alerts')
def api_runtime_alerts():
    """Only high-priority runtime alerts with CVE+fix context."""
    runtime = load_runtime_findings()
    return jsonify(runtime.get("alerts", []))


@app.route('/api/runtime-threats/container/<name>')
def api_runtime_container_detail(name):
    """Container-level runtime detail including CVEs and suggested fixes."""
    item = runtime_summary_by_container(name)
    if item:
        return jsonify(item)
    return jsonify({"error": "container not found"}), 404


@app.route('/api/control-panel/report/runtime', methods=['POST'])
def api_control_panel_runtime_report():
    """Generate runtime security report on-demand (json/txt)."""
    payload = request.get_json(silent=True) or {}
    fmt = payload.get("format", "json")
    if fmt not in {"json", "txt"}:
        return jsonify({"success": False, "error": "format must be json or txt"}), 400

    runtime = load_runtime_findings()
    if not runtime.get("generated_at"):
        return jsonify({"success": False, "error": "no runtime findings available"}), 404

    try:
        engine = runtime_engine_instance()
        path = engine.generate_report(runtime, fmt=fmt)
        return jsonify({"success": True, "format": fmt, "path": str(path)})
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc)}), 500


@app.route('/reports/<filename>')
def download_report(filename):
    """Download specific report file"""
    filepath = REPORTS_DIR / filename
    if filepath.exists():
        return send_file(filepath, as_attachment=True)
    return jsonify({"error": "File not found"}), 404


@app.route('/health')
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "timestamp": datetime.now().isoformat()})


if __name__ == '__main__':
    # Create reports directory if it doesn't exist
    REPORTS_DIR.mkdir(exist_ok=True)
    RUNTIME_DIR.mkdir(exist_ok=True)
    
    print("=" * 70)
    print("🔒 Container Security Audit Dashboard")
    print("=" * 70)
    print(f"📊 Dashboard URL: http://localhost:8080")
    print(f"📁 Reports Directory: {REPORTS_DIR.absolute()}")
    print("=" * 70)
    
    app.run(host='0.0.0.0', port=8080, debug=True)
